--------------------------------------------------------
--  File created - Wednesday-June-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."ADDRESS" 
   (	"ADD_ID" NUMBER(*,0), 
	"ADD_CITY" VARCHAR2(32 CHAR), 
	"ADD_COUNTRY" VARCHAR2(32 CHAR), 
	"ADD_CODEPOST" NUMBER(*,0), 
	"ADD_STREET" NUMBER(*,0), 
	"ADD_HOUSENO" NUMBER(*,0), 
	"PERSONV1_P_ID" NUMBER(*,0), 
	"VENUE_V_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."ADMIN" 
   (	"P_ID" NUMBER(*,0), 
	"AD_ID" NUMBER(*,0), 
	"AD_PASSWORD" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENT
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."EQUIPMENT" 
   (	"E_ID" NUMBER(*,0), 
	"E_NAME" VARCHAR2(32 CHAR), 
	"PLAYER_P_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."GAME" 
   (	"G_NAME" VARCHAR2(32 CHAR), 
	"G_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATCHES
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."MATCHES" 
   (	"M_ID" NUMBER(*,0), 
	"M_DATE" DATE, 
	"TOURNAMENT_TOU_ID" NUMBER(*,0), 
	"VENUE_V_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."PERSON" 
   (	"P_ID" NUMBER(*,0), 
	"P_NAME" VARCHAR2(32 CHAR), 
	"P_EMAIL" VARCHAR2(32 CHAR), 
	"P_DOB" NUMBER(*,0), 
	"P_GENDER" VARCHAR2(32 CHAR), 
	"P_CNIC" NUMBER(*,0), 
	"PERSON_TYPE" VARCHAR2(7 BYTE), 
	"P_PASSWORD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."PLAYER" 
   (	"P_ID" NUMBER(*,0), 
	"PL_EXPERIENCE" NUMBER(*,0), 
	"TEAM_TE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYS
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."PLAYS" 
   (	"TEAM_TE_ID" NUMBER(*,0), 
	"TOURNAMENT_TOU_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TEAM" 
   (	"T_ID" NUMBER(*,0), 
	"T_NAME" VARCHAR2(32 CHAR), 
	"T_FORMDATE" VARCHAR2(32 BYTE), 
	"T_GAME_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM_PL_TOUR
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TEAM_PL_TOUR" 
   (	"TEAM_TE_ID" NUMBER(*,0), 
	"TOURNAMENT_TOU_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM_TRAINER
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TEAM_TRAINER" 
   (	"TEAM_TE_ID" NUMBER(*,0), 
	"TRAINER_P_ID" NUMBER(*,0), 
	"TODATE" DATE, 
	"FROMDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table team-match
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."team-match" 
   (	"TEAM_TE_ID" NUMBER(*,0), 
	"MATCHESV1_M_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOURNAMENT
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TOURNAMENT" 
   (	"T_ID" NUMBER(*,0), 
	"T_NAME" VARCHAR2(32 CHAR), 
	"T_YEAR" NUMBER(*,0), 
	"T_TODATE" VARCHAR2(20 BYTE), 
	"T_FROMDATE" VARCHAR2(20 BYTE), 
	"T_GAME_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAIN_TEAM
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TRAIN_TEAM" 
   (	"TEAM_TE_ID" NUMBER(*,0), 
	"TRAINING_SESSION_TR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAINER
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TRAINER" 
   (	"P_ID" NUMBER(*,0), 
	"T_EXPERIENCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAINING_SESSION
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."TRAINING_SESSION" 
   (	"TR_ID" NUMBER(*,0), 
	"TR_DATE" DATE, 
	"VENUE_V_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENUE
--------------------------------------------------------

  CREATE TABLE "KHADIJA"."VENUE" 
   (	"V_NAME" VARCHAR2(32 CHAR), 
	"V_CONTACTNO" NUMBER(*,0), 
	"V_ID" NUMBER(*,0), 
	"V_ADDRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."ADDRESS__IDX" ON "KHADIJA"."ADDRESS" ("PERSONV1_P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS__IDXV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."ADDRESS__IDXV1" ON "KHADIJA"."ADDRESS" ("VENUE_V_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."ADDRESS_PK" ON "KHADIJA"."ADDRESS" ("ADD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."ADMIN_PK" ON "KHADIJA"."ADMIN" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."ADMIN_PKV1" ON "KHADIJA"."ADMIN" ("AD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."EQUIPMENT_PK" ON "KHADIJA"."EQUIPMENT" ("E_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."GAME_PK" ON "KHADIJA"."GAME" ("G_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MATCHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."MATCHES_PK" ON "KHADIJA"."MATCHES" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."PERSON_PK" ON "KHADIJA"."PERSON" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."PLAYER_PK" ON "KHADIJA"."PLAYER" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAYS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."PLAYS_PK" ON "KHADIJA"."PLAYS" ("TEAM_TE_ID", "TOURNAMENT_TOU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TEAM_PK" ON "KHADIJA"."TEAM" ("T_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAM_PL_TOUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TEAM_PL_TOUR_PK" ON "KHADIJA"."TEAM_PL_TOUR" ("TEAM_TE_ID", "TOURNAMENT_TOU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAM_TRAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TEAM_TRAINER_PK" ON "KHADIJA"."TEAM_TRAINER" ("TEAM_TE_ID", "TRAINER_P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index team-match_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."team-match_PK" ON "KHADIJA"."team-match" ("TEAM_TE_ID", "MATCHESV1_M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOURNAMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TOURNAMENT_PK" ON "KHADIJA"."TOURNAMENT" ("T_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAIN_TEAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TRAIN_TEAM_PK" ON "KHADIJA"."TRAIN_TEAM" ("TEAM_TE_ID", "TRAINING_SESSION_TR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TRAINER_PK" ON "KHADIJA"."TRAINER" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAINING_SESSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."TRAINING_SESSION_PK" ON "KHADIJA"."TRAINING_SESSION" ("TR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHADIJA"."VENUE_PK" ON "KHADIJA"."VENUE" ("V_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_4_ADMIN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KHADIJA"."ARC_FKARC_4_ADMIN" BEFORE
    INSERT OR UPDATE OF p_id ON admin
    FOR EACH ROW
DECLARE
    d   VARCHAR2(7);
BEGIN
    SELECT
        a.personv1_type
    INTO d
    FROM
        personv1 a
    WHERE
        a.p_id = :new.p_id;

    IF ( d IS NULL OR d <> 'Admin' ) THEN
        raise_application_error(-20223, 'FK Admin_Personv1_FK in Table Admin violates Arc constraint on Table Personv1 - discriminator column Personv1_TYPE doesn''t have value ''Admin'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "KHADIJA"."ARC_FKARC_4_ADMIN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_4_PLAYER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KHADIJA"."ARC_FKARC_4_PLAYER" BEFORE
    INSERT OR UPDATE OF p_id ON player
    FOR EACH ROW
DECLARE
    d   VARCHAR2(7);
BEGIN
    SELECT
        a.personv1_type
    INTO d
    FROM
        personv1 a
    WHERE
        a.p_id = :new.p_id;

    IF ( d IS NULL OR d <> 'Player' ) THEN
        raise_application_error(-20223, 'FK Player_Personv1_FK in Table Player violates Arc constraint on Table Personv1 - discriminator column Personv1_TYPE doesn''t have value ''Player'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "KHADIJA"."ARC_FKARC_4_PLAYER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_2_TRAINER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KHADIJA"."ARC_FKARC_2_TRAINER" BEFORE
    INSERT OR UPDATE OF p_id ON trainer
    FOR EACH ROW
DECLARE
    d   VARCHAR2(7);
BEGIN
    SELECT
        a.person_type
    INTO d
    FROM
        person a
    WHERE
        a.p_id = :new.p_id;

    IF ( d IS NULL OR d <> 'Trainer' ) THEN
        raise_application_error(-20223, 'FK Trainer_Person_FK in Table Trainer violates Arc constraint on Table Person - discriminator column Person_TYPE doesn''t have value ''Trainer'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "KHADIJA"."ARC_FKARC_2_TRAINER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("VENUE_V_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("PERSONV1_P_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_HOUSENO" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_STREET" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_CODEPOST" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_CITY" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADDRESS" MODIFY ("ADD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."ADMIN" ADD CONSTRAINT "ADMIN_PKV1" UNIQUE ("AD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."ADMIN" MODIFY ("AD_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADMIN" MODIFY ("AD_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."ADMIN" MODIFY ("P_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_PK" PRIMARY KEY ("E_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."EQUIPMENT" MODIFY ("PLAYER_P_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."EQUIPMENT" MODIFY ("E_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."EQUIPMENT" MODIFY ("E_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."GAME" ADD CONSTRAINT "GAME_PK" PRIMARY KEY ("G_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."GAME" MODIFY ("G_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."GAME" MODIFY ("G_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATCHES
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."MATCHES" ADD CONSTRAINT "MATCHES_PK" PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."MATCHES" MODIFY ("VENUE_V_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."MATCHES" MODIFY ("TOURNAMENT_TOU_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."MATCHES" MODIFY ("M_DATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."MATCHES" MODIFY ("M_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."PERSON" ADD CONSTRAINT "CH_INH_PERSON" CHECK ( person_type IN (
        'Admin',
        'Person',
        'Player',
        'Trainer'
    ) ) ENABLE;
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_CNIC" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_GENDER" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_DOB" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PERSON" MODIFY ("P_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."PLAYER" ADD CONSTRAINT "PLAYER_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."PLAYER" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PLAYER" MODIFY ("PL_EXPERIENCE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PLAYER" MODIFY ("P_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYS
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."PLAYS" ADD CONSTRAINT "PLAYS_PK" PRIMARY KEY ("TEAM_TE_ID", "TOURNAMENT_TOU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."PLAYS" MODIFY ("TOURNAMENT_TOU_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."PLAYS" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TEAM" ADD CONSTRAINT "TEAM_PK" PRIMARY KEY ("T_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TEAM" MODIFY ("T_FORMDATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM" MODIFY ("T_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM" MODIFY ("T_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM_PL_TOUR
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TEAM_PL_TOUR" ADD CONSTRAINT "TEAM_PL_TOUR_PK" PRIMARY KEY ("TEAM_TE_ID", "TOURNAMENT_TOU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TEAM_PL_TOUR" MODIFY ("TOURNAMENT_TOU_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM_PL_TOUR" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM_TRAINER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TEAM_TRAINER" ADD CONSTRAINT "TEAM_TRAINER_PK" PRIMARY KEY ("TEAM_TE_ID", "TRAINER_P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TEAM_TRAINER" MODIFY ("FROMDATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM_TRAINER" MODIFY ("TODATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM_TRAINER" MODIFY ("TRAINER_P_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TEAM_TRAINER" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table team-match
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."team-match" ADD CONSTRAINT "team-match_PK" PRIMARY KEY ("TEAM_TE_ID", "MATCHESV1_M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."team-match" MODIFY ("MATCHESV1_M_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."team-match" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOURNAMENT
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TOURNAMENT" ADD CONSTRAINT "TOURNAMENT_PK" PRIMARY KEY ("T_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_GAME_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_FROMDATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_TODATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_YEAR" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TOURNAMENT" MODIFY ("T_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAIN_TEAM
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TRAIN_TEAM" ADD CONSTRAINT "TRAIN_TEAM_PK" PRIMARY KEY ("TEAM_TE_ID", "TRAINING_SESSION_TR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TRAIN_TEAM" MODIFY ("TRAINING_SESSION_TR_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TRAIN_TEAM" MODIFY ("TEAM_TE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAINER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TRAINER" ADD CONSTRAINT "TRAINER_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TRAINER" MODIFY ("T_EXPERIENCE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TRAINER" MODIFY ("P_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAINING_SESSION
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TRAINING_SESSION" ADD CONSTRAINT "TRAINING_SESSION_PK" PRIMARY KEY ("TR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."TRAINING_SESSION" MODIFY ("VENUE_V_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TRAINING_SESSION" MODIFY ("TR_DATE" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."TRAINING_SESSION" MODIFY ("TR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENUE
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."VENUE" MODIFY ("V_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."VENUE" ADD CONSTRAINT "VENUE_PK" PRIMARY KEY ("V_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHADIJA"."VENUE" MODIFY ("V_ID" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."VENUE" MODIFY ("V_CONTACTNO" NOT NULL ENABLE);
  ALTER TABLE "KHADIJA"."VENUE" MODIFY ("V_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_PLAYER_FK" FOREIGN KEY ("PLAYER_P_ID")
	  REFERENCES "KHADIJA"."PLAYER" ("P_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCHES
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."MATCHES" ADD CONSTRAINT "MATCHES_TOURNAMENT_FK" FOREIGN KEY ("TOURNAMENT_TOU_ID")
	  REFERENCES "KHADIJA"."TOURNAMENTV2" ("TOU_ID") ENABLE;
  ALTER TABLE "KHADIJA"."MATCHES" ADD CONSTRAINT "MATCHES_VENUE_FK" FOREIGN KEY ("VENUE_V_ID")
	  REFERENCES "KHADIJA"."VENUEV2" ("V_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."PLAYER" ADD CONSTRAINT "PLAYER_TEAM_FK" FOREIGN KEY ("TEAM_TE_ID")
	  REFERENCES "KHADIJA"."TEAM" ("T_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYS
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."PLAYS" ADD CONSTRAINT "PLAYS_TEAM_FK" FOREIGN KEY ("TEAM_TE_ID")
	  REFERENCES "KHADIJA"."TEAMV2" ("TE_ID") ENABLE;
  ALTER TABLE "KHADIJA"."PLAYS" ADD CONSTRAINT "PLAYS_TOURNAMENT_FK" FOREIGN KEY ("TOURNAMENT_TOU_ID")
	  REFERENCES "KHADIJA"."TOURNAMENTV2" ("TOU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAM_PL_TOUR
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TEAM_PL_TOUR" ADD CONSTRAINT "TEAM_PL_TOUR_TEAM_FK" FOREIGN KEY ("TEAM_TE_ID")
	  REFERENCES "KHADIJA"."TEAM" ("T_ID") ENABLE;
  ALTER TABLE "KHADIJA"."TEAM_PL_TOUR" ADD CONSTRAINT "TEAM_PL_TOUR_TOURNAMENT_FK" FOREIGN KEY ("TOURNAMENT_TOU_ID")
	  REFERENCES "KHADIJA"."TOURNAMENT" ("T_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAM_TRAINER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TEAM_TRAINER" ADD CONSTRAINT "TEAM_TRAINER_TEAM_FK" FOREIGN KEY ("TEAM_TE_ID")
	  REFERENCES "KHADIJA"."TEAMV2" ("TE_ID") ENABLE;
  ALTER TABLE "KHADIJA"."TEAM_TRAINER" ADD CONSTRAINT "TEAM_TRAINER_TRAINER_FK" FOREIGN KEY ("TRAINER_P_ID")
	  REFERENCES "KHADIJA"."TRAINER" ("P_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table team-match
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."team-match" ADD CONSTRAINT "team-match_Matchesv1_FK" FOREIGN KEY ("MATCHESV1_M_ID")
	  REFERENCES "KHADIJA"."MATCHESV1" ("M_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAIN_TEAM
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TRAIN_TEAM" ADD CONSTRAINT "TRAIN_TEAM_TEAM_FK" FOREIGN KEY ("TEAM_TE_ID")
	  REFERENCES "KHADIJA"."TEAM" ("T_ID") ENABLE;
  ALTER TABLE "KHADIJA"."TRAIN_TEAM" ADD CONSTRAINT "TRAIN_TEAM_TRAINING_SESSION_FK" FOREIGN KEY ("TRAINING_SESSION_TR_ID")
	  REFERENCES "KHADIJA"."TRAINING_SESSION" ("TR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAINER
--------------------------------------------------------

  ALTER TABLE "KHADIJA"."TRAINER" ADD CONSTRAINT "TRAINER_PERSON_FK" FOREIGN KEY ("P_ID")
	  REFERENCES "KHADIJA"."PERSON" ("P_ID") ENABLE;
